### ISSUE TITLE
논의 undefined method 'proposal_with_deleted' for nil:NilClass

### ISSUE THREAD

**Issue by mozodev** [parti-xyz/canoe-web#44]
```
​*An exception occurred while doing*​: `GET </app/discussions/33>`
Exception
----------------
undefined method 'proposal_with_deleted' for nil:NilClass

Backtrace
----------------
```/data/canoe_web/releases/20160125063633/app/views/public_activity/votes/_in_favor.html.haml:4:in `_app_views_public_activity_votes__in_favor_html_haml___3004062794565523498_70015759780040'
/data/canoe_web/shared/bundled_gems/ruby/2.2.0/gems/actionview-4.2.5/lib/action_view/template.rb:145:in `block in render'
/data/canoe_web/shared/bundled_gems/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/notifications.rb:166:in `instrument'
/data/canoe_web/shared/bundled_gems/ruby/2.2.0/gems/actionview-4.2.5/lib/action_view/template.rb:333:in `instrument'
/data/canoe_web/shared/bundled_gems/ruby/2.2.0/gems/actionview-4.2.5/lib/action_view/template.rb:143:in `render
```

**Comment by dalikim** [comment]
아 이슈가 있었군요. 그냥 커밋했는데. 닫을께요.
